# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  Dataframes.Repo.Path: $(Build.SourcesDirectory) # this one is required by the build script
jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: |
      "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --wait --passive --norestart --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise" --add Microsoft.VisualStudio.Component.VC.Tools.14.15
      echo Result %ERRORLEVEL%
      copy %temp%\dd* $(Build.ArtifactStagingDirectory)
      dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Dataframes-Win-x64